modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "yunbeiuc"
version = "${version}"
displayName = "Yunbei Urban Construction"
authors = "北咕, jstxjf_, 潇湘-迷蝎, Tizhengxie, NanGuaQWQ, CR400BF_G_5133，Yomi_307"
description = '''
Let's use the mod to decorate your city!
'''

[[dependencies.yunbeiuc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yunbeiuc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yunbeiuc]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
