package com.beigu.yunbeiuc.block;

import com.beigu.yunbeiuc.YunbeiUrbanConstruction;
import com.beigu.yunbeiuc.block.custom.sign.*;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.registry.RegistryKeys;

public class SignBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(YunbeiUrbanConstruction.MOD_ID, RegistryKeys.BLOCK);
    public static final RegistrySupplier<Block> SIGN_STOP = BLOCKS.register("sign_stop", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_YIELD = BLOCKS.register("sign_yield", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_YIELD_TO_ONCOMING_TRAFFIC = BLOCKS.register("sign_yield_to_oncoming_traffic", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_ALL = BLOCKS.register("sign_no_all", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_ENTRY = BLOCKS.register("sign_no_entry", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_NO_MOTOR_VEHICLES = BLOCKS.register("sign_no_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_LARGE_BUS = BLOCKS.register("sign_no_large_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_SMALL_PASSENGER_CAR = BLOCKS.register("sign_no_small_passenger_car", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_TRUCK = BLOCKS.register("sign_no_truck", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_TRAILER = BLOCKS.register("sign_no_trailer", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_TRACTOR = BLOCKS.register("sign_no_tractor", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_THREE_WHEELED_VEHICLE = BLOCKS.register("sign_no_three_wheeled_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_MOTORCYCLE = BLOCKS.register("sign_no_motorcycle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_NON_MOTOR_VEHICLES = BLOCKS.register("sign_no_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_ELECTRIC_VEHICLE = BLOCKS.register("sign_no_electric_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_ANIMAL_DRAWN_CART = BLOCKS.register("sign_no_animal_drawn_cart", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_TRICYCLE = BLOCKS.register("sign_no_tricycle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_HUMAN_POWERED_PASSENGER_TRICYCLE = BLOCKS.register("sign_no_human_powered_passenger_tricycle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_HUMAN_POWERED_CARGO_TRICYCLE = BLOCKS.register("sign_no_human_powered_cargo_tricycle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_RICKSHAW = BLOCKS.register("sign_no_rickshaw", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_PEDESTRIAN = BLOCKS.register("sign_no_pedestrian", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_NO_LEFT_TURN = BLOCKS.register("sign_no_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_STRAIGHT = BLOCKS.register("sign_no_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_RIGHT_TURN = BLOCKS.register("sign_no_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_LEFT_RIGHT_TURN = BLOCKS.register("sign_no_left_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_STRAIGHT_LEFT_TURN = BLOCKS.register("sign_no_straight_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_STRAIGHT_RIGHT_TURN = BLOCKS.register("sign_no_straight_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_SINGLE_LEFT_TURN_AROUND = BLOCKS.register("sign_no_single_left_turn_around", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_NO_OVERTAKE = BLOCKS.register("sign_no_overtake", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_OVERTAKE = BLOCKS.register("sign_cancel_overtake", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_PARKING = BLOCKS.register("sign_no_parking", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_PARKING_LONG_TIME = BLOCKS.register("sign_no_parking_long_time", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_HONK_HORN = BLOCKS.register("sign_no_honk_horn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_20 = BLOCKS.register("sign_width_limit_20", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_25 = BLOCKS.register("sign_width_limit_25", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_30 = BLOCKS.register("sign_width_limit_30", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_35 = BLOCKS.register("sign_width_limit_35", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_40 = BLOCKS.register("sign_width_limit_40", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WIDTH_LIMIT_45 = BLOCKS.register("sign_width_limit_45", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_20 = BLOCKS.register("sign_height_limit_20", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_25 = BLOCKS.register("sign_height_limit_25", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_30 = BLOCKS.register("sign_height_limit_30", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_35 = BLOCKS.register("sign_height_limit_35", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_40 = BLOCKS.register("sign_height_limit_40", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_HEIGHT_LIMIT_45 = BLOCKS.register("sign_height_limit_45", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WEIGHT_LIMIT_10 = BLOCKS.register("sign_weight_limit_10", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WEIGHT_LIMIT_20 = BLOCKS.register("sign_weight_limit_20", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WEIGHT_LIMIT_30 = BLOCKS.register("sign_weight_limit_30", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WEIGHT_LIMIT_40 = BLOCKS.register("sign_weight_limit_40", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_ALEX_WEIGHT_LIMIT_10 = BLOCKS.register("sign_alex_weight_limit_10", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_ALEX_WEIGHT_LIMIT_20 = BLOCKS.register("sign_alex_weight_limit_20", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_ALEX_WEIGHT_LIMIT_30 = BLOCKS.register("sign_alex_weight_limit_30", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_005 = BLOCKS.register("sign_speed_limit_005", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_010 = BLOCKS.register("sign_speed_limit_010", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_020 = BLOCKS.register("sign_speed_limit_020", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_030 = BLOCKS.register("sign_speed_limit_030", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_040 = BLOCKS.register("sign_speed_limit_040", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_050 = BLOCKS.register("sign_speed_limit_050", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_060 = BLOCKS.register("sign_speed_limit_060", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_070 = BLOCKS.register("sign_speed_limit_070", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_080 = BLOCKS.register("sign_speed_limit_080", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_090 = BLOCKS.register("sign_speed_limit_090", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_100 = BLOCKS.register("sign_speed_limit_100", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_110 = BLOCKS.register("sign_speed_limit_110", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_SPEED_LIMIT_120 = BLOCKS.register("sign_speed_limit_120", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_005 = BLOCKS.register("sign_cancel_speed_limit_005", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_010 = BLOCKS.register("sign_cancel_speed_limit_010", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_020 = BLOCKS.register("sign_cancel_speed_limit_020", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_030 = BLOCKS.register("sign_cancel_speed_limit_030", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_040 = BLOCKS.register("sign_cancel_speed_limit_040", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_050 = BLOCKS.register("sign_cancel_speed_limit_050", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_060 = BLOCKS.register("sign_cancel_speed_limit_060", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_070 = BLOCKS.register("sign_cancel_speed_limit_070", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_080 = BLOCKS.register("sign_cancel_speed_limit_080", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_090 = BLOCKS.register("sign_cancel_speed_limit_090", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_100 = BLOCKS.register("sign_cancel_speed_limit_100", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_110 = BLOCKS.register("sign_cancel_speed_limit_110", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_CANCEL_SPEED_LIMIT_120 = BLOCKS.register("sign_cancel_speed_limit_120", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_CHECK = BLOCKS.register("sign_check", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_PORT_CHECK = BLOCKS.register("sign_port_check", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_NO_HAZARDOUS_MATERIALS_TRANSPORT_VEHICLE = BLOCKS.register("sign_no_hazardous_materials_transport_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_STRAIGHT = BLOCKS.register("sign_indication_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LEFT_TURN = BLOCKS.register("sign_indication_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_RIGHT_TURN = BLOCKS.register("sign_indication_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_STRAIGHT_LEFT_TURN = BLOCKS.register("sign_indication_straight_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_STRAIGHT_RIGHT_TURN = BLOCKS.register("sign_indication_straight_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LEFT_RIGHT_TURN = BLOCKS.register("sign_indication_left_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_ROUNDABOUT = BLOCKS.register("sign_indication_roundabout", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_ONE_WAY_STREET_LEFT_RIGHT = BLOCKS.register("sign_indication_one_way_street_left_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_ONE_WAY_STREET_STRAIGHT = BLOCKS.register("sign_indication_one_way_street_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_HONK_HORN = BLOCKS.register("sign_indication_honk_horn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_HEADLIGHTS = BLOCKS.register("sign_indication_headlights", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_005 = BLOCKS.register("sign_min_speed_limit_005", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_010 = BLOCKS.register("sign_min_speed_limit_010", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_020 = BLOCKS.register("sign_min_speed_limit_020", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_030 = BLOCKS.register("sign_min_speed_limit_030", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_040 = BLOCKS.register("sign_min_speed_limit_040", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_050 = BLOCKS.register("sign_min_speed_limit_050", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_060 = BLOCKS.register("sign_min_speed_limit_060", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_070 = BLOCKS.register("sign_min_speed_limit_070", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_080 = BLOCKS.register("sign_min_speed_limit_080", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_090 = BLOCKS.register("sign_min_speed_limit_090", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_MIN_SPEED_LIMIT_100 = BLOCKS.register("sign_min_speed_limit_100", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_YIELD_TO_ONCOMING_TRAFFIC = BLOCKS.register("sign_indication_yield_to_oncoming_traffic", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_ZEBRA_CROSSING = BLOCKS.register("sign_indication_zebra_crossing", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_ZEBRA_CROSSING_FLUORESCENCE = BLOCKS.register("sign_indication_zebra_crossing_fluorescence", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_RIGHT_TURN = BLOCKS.register("sign_indication_lane_direction_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN = BLOCKS.register("sign_indication_lane_direction_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_RIGHT_TURN = BLOCKS.register("sign_indication_lane_direction_straight_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_LEFT_TURN = BLOCKS.register("sign_indication_lane_direction_straight_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_SINGLE_LEFT_TURN_AROUND = BLOCKS.register("sign_indication_lane_direction_single_left_turn_around", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN_AROUND = BLOCKS.register("sign_indication_lane_direction_left_turn_around", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_MOTOR_VEHICLES = BLOCKS.register("sign_indication_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES = BLOCKS.register("sign_indication_lane_direction_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_motor_vehicles_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_motor_vehicles_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_motor_vehicles_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR = BLOCKS.register("sign_indication_lane_direction_small_passenger_car", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_small_passenger_car_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_small_passenger_car_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_small_passenger_car_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS = BLOCKS.register("sign_indication_lane_direction_large_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_large_bus_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT = BLOCKS.register("sign_indication_lane_direction_large_bus_text", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_large_bus_text_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_text_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_text_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT = BLOCKS.register("sign_indication_lane_direction_large_bus_brt", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_large_bus_brt_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_brt_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_large_bus_brt_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_TRAM_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_tram_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_HOV = BLOCKS.register("sign_indication_lane_direction_hov", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_NON_MOTOR_VEHICLES = BLOCKS.register("sign_indication_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES = BLOCKS.register("sign_indication_lane_direction_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_non_motor_vehicles_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_non_motor_vehicles_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_non_motor_vehicles_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_ELECTRIC_VEHICLE = BLOCKS.register("sign_indication_electric_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE = BLOCKS.register("sign_indication_lane_direction_electric_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_STRAIGHT = BLOCKS.register("sign_indication_lane_direction_electric_vehicle_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_LEFT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_electric_vehicle_left_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_RIGHT_SIDE_MEDIAN_STRIP = BLOCKS.register("sign_indication_lane_direction_electric_vehicle_right_side_median_strip", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_PEDESTRIAN = BLOCKS.register("sign_indication_pedestrian", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_1 = BLOCKS.register("sign_indication_pedestrian_non_motor_vehicles_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_2 = BLOCKS.register("sign_indication_pedestrian_non_motor_vehicles_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_3 = BLOCKS.register("sign_indication_pedestrian_non_motor_vehicles_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_PROMOTION_NON_MOTOR_VEHICLES = BLOCKS.register("sign_indication_promotion_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PROMOTION_DRIVE_RIGHT = BLOCKS.register("sign_indication_promotion_drive_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_1 = BLOCKS.register("sign_indication_parking_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_2 = BLOCKS.register("sign_indication_parking_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_3 = BLOCKS.register("sign_indication_parking_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_4 = BLOCKS.register("sign_indication_parking_4", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_DISABLED = BLOCKS.register("sign_indication_parking_disabled", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_SCHOOL_BUS = BLOCKS.register("sign_indication_parking_school_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_SCHOOL_BUS_WUXI = BLOCKS.register("sign_indication_school_bus_wuxi", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_SCHOOL_BUS_FLUORESCENCE = BLOCKS.register("sign_indication_parking_school_bus_fluorescence", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_TAXI = BLOCKS.register("sign_indication_parking_taxi", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_NON_MOTOR_VEHICLE = BLOCKS.register("sign_indication_parking_non_motor_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_BUS = BLOCKS.register("sign_indication_parking_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_CHARGING = BLOCKS.register("sign_indication_parking_charging", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PARKING_COMPANY = BLOCKS.register("sign_indication_parking_company", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_TURN_AROUND = BLOCKS.register("sign_indication_turn_around", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_PAVED_SHOULDER_1 = BLOCKS.register("sign_indication_paved_shoulder_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PAVED_SHOULDER_2 = BLOCKS.register("sign_indication_paved_shoulder_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_INDICATION_PAVED_SHOULDER_3 = BLOCKS.register("sign_indication_paved_shoulder_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_INDICATION_OK_TRUCK = BLOCKS.register("sign_indication_ok_truck", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_1 = BLOCKS.register("sign_warning_crossing_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_2 = BLOCKS.register("sign_warning_crossing_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_3 = BLOCKS.register("sign_warning_crossing_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_4 = BLOCKS.register("sign_warning_crossing_4", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_5 = BLOCKS.register("sign_warning_crossing_5", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_6 = BLOCKS.register("sign_warning_crossing_6", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_7 = BLOCKS.register("sign_warning_crossing_7", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_8 = BLOCKS.register("sign_warning_crossing_8", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_9 = BLOCKS.register("sign_warning_crossing_9", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_10 = BLOCKS.register("sign_warning_crossing_10", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSING_11 = BLOCKS.register("sign_warning_crossing_11", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_SHARP_TURN_1 = BLOCKS.register("sign_warning_sharp_turn_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_SHARP_TURN_2 = BLOCKS.register("sign_warning_sharp_turn_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_REVERSE_DETOUR_1 = BLOCKS.register("sign_warning_reverse_detour_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_REVERSE_DETOUR_2 = BLOCKS.register("sign_warning_reverse_detour_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CONTINUOUS_WINDING_ROADS_1 = BLOCKS.register("sign_warning_continuous_winding_roads_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CONTINUOUS_WINDING_ROADS_2 = BLOCKS.register("sign_warning_continuous_winding_roads_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_STEEP_SLOPE_UP = BLOCKS.register("sign_warning_steep_slope_up", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_STEEP_SLOPE_DOWN = BLOCKS.register("sign_warning_steep_slope_down", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CONTINUOUS_DOWNHILL = BLOCKS.register("sign_warning_continuous_downhill", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_NARROW_ROAD_DOUBLE = BLOCKS.register("sign_warning_narrow_road_double", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_NARROW_ROAD_LEFT = BLOCKS.register("sign_warning_narrow_road_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_NARROW_ROAD_RIGHT = BLOCKS.register("sign_warning_narrow_road_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_NARROW_BRIDGE = BLOCKS.register("sign_warning_narrow_bridge", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_TWO_WAY_TRAFFIC = BLOCKS.register("sign_warning_two_way_traffic", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_ZEBRA_CROSSING = BLOCKS.register("sign_warning_zebra_crossing", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_ZEBRA_CROSSING_FLUORESCENCE = BLOCKS.register("sign_warning_zebra_crossing_fluorescence", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CHILDREN = BLOCKS.register("sign_warning_children", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CHILDREN_FLUORESCENCE = BLOCKS.register("sign_warning_children_fluorescence", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_DISABLED = BLOCKS.register("sign_warning_disabled", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_DISABLED_FLUORESCENCE = BLOCKS.register("sign_warning_disabled_fluorescence", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_NON_MOTOR_VEHICLES = BLOCKS.register("sign_warning_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_ELECTRIC_VEHICLE = BLOCKS.register("sign_warning_electric_vehicle", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LIVESTOCK = BLOCKS.register("sign_warning_livestock", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_WILDLIFE = BLOCKS.register("sign_warning_wildlife", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_TRAFFIC_LIGHTS = BLOCKS.register("sign_warning_traffic_lights", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_FALLING_ROCKS_LEFT = BLOCKS.register("sign_warning_falling_rocks_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_FALLING_ROCKS_RIGHT = BLOCKS.register("sign_warning_falling_rocks_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CROSSWIND = BLOCKS.register("sign_warning_crosswind", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_SLIPPERY = BLOCKS.register("sign_warning_slippery", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_LEFT = BLOCKS.register("sign_warning_perilous_road_along_the_mountain_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_RIGHT = BLOCKS.register("sign_warning_perilous_road_along_the_mountain_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_EMBANKMENT_ROAD_LEFT = BLOCKS.register("sign_warning_embankment_road_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_EMBANKMENT_ROAD_RIGHT = BLOCKS.register("sign_warning_embankment_road_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_VILLAGE = BLOCKS.register("sign_warning_village", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_TUNNEL = BLOCKS.register("sign_warning_tunnel", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CAMEL_BACK_BRIDGE = BLOCKS.register("sign_warning_camel_back_bridge", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_ROAD_UNEVEN = BLOCKS.register("sign_warning_road_uneven", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_SPEED_BUMP = BLOCKS.register("sign_warning_speed_bump", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_ROAD_WET = BLOCKS.register("sign_warning_road_wet", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_SOMEONE_GUARDING_THE_RAILWAY_CROSSING = BLOCKS.register("sign_warning_someone_guarding_the_railway_crossing", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_UNMANNED_GUARDING_THE_RAILWAY_CROSSING = BLOCKS.register("sign_warning_unmanned_guarding_the_railway_crossing", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_ACCIDENT_PRONE_ROAD = BLOCKS.register("sign_warning_accident_prone_road", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_DETOUR_DOUBLE = BLOCKS.register("sign_warning_detour_double", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_DETOUR_LEFT = BLOCKS.register("sign_warning_detour_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_DETOUR_RIGHT = BLOCKS.register("sign_warning_detour_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_DANGEROUS = BLOCKS.register("sign_warning_dangerous", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CONSTRUCTION = BLOCKS.register("sign_warning_construction", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_ACCIDENT = BLOCKS.register("sign_warning_accident", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_TIDAL_LANE = BLOCKS.register("sign_warning_tidal_lane", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_DISTANCE_BETWEEN_VEHICLES = BLOCKS.register("sign_warning_distance_between_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_CONFLUENCE_LEFT = BLOCKS.register("sign_warning_confluence_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_CONFLUENCE_RIGHT = BLOCKS.register("sign_warning_confluence_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_LESS_3_TO_2 = BLOCKS.register("sign_warning_less_3_to_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LESS_4_TO_3 = BLOCKS.register("sign_warning_less_4_to_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_EMERGENCY_LANE_1 = BLOCKS.register("sign_warning_emergency_lane_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_EMERGENCY_LANE_2 = BLOCKS.register("sign_warning_emergency_lane_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_ROAD_ICY = BLOCKS.register("sign_warning_road_icy", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_WEATHER_RAINY_SNOWY = BLOCKS.register("sign_warning_weather_rainy_snowy", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_WEATHER_FOGGY = BLOCKS.register("sign_warning_weather_foggy", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_WEATHER_THUNDER = BLOCKS.register("sign_warning_weather_thunder", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_VEHICLES_QUEUED_AHEAD = BLOCKS.register("sign_warning_vehicles_queued_ahead", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_1 = BLOCKS.register("sign_warning_linear_guidance_marker_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_2 = BLOCKS.register("sign_warning_linear_guidance_marker_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_3 = BLOCKS.register("sign_warning_linear_guidance_marker_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_4 = BLOCKS.register("sign_warning_linear_guidance_marker_4", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_5 = BLOCKS.register("sign_warning_linear_guidance_marker_5", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_6 = BLOCKS.register("sign_warning_linear_guidance_marker_6", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_7 = BLOCKS.register("sign_warning_linear_guidance_marker_7", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_8 = BLOCKS.register("sign_warning_linear_guidance_marker_8", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_WARNING_LINEAR_GUIDANCE_MARKER_9 = BLOCKS.register("sign_warning_linear_guidance_marker_9", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> ZONES_BOARD_RED = BLOCKS.register("zones_board_red", () -> new ZonesBoard1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_YELLOW = BLOCKS.register("zones_board_yellow", () -> new ZonesBoard1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_WHITE = BLOCKS.register("zones_board_white", () -> new ZonesBoard1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_LEFT = BLOCKS.register("zones_board_arrow_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_RIGHT = BLOCKS.register("zones_board_arrow_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_LEFT_RIGHT = BLOCKS.register("zones_board_arrow_left_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_STRAIGHT = BLOCKS.register("zones_board_arrow_straight", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_LEFT_TURN = BLOCKS.register("zones_board_arrow_left_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_ARROW_RIGHT_TURN = BLOCKS.register("zones_board_arrow_right_turn", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_BUS = BLOCKS.register("zones_board_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_SCHOOL_BUS_1 = BLOCKS.register("zones_board_school_bus_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_SCHOOL_BUS_2 = BLOCKS.register("zones_board_school_bus_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TAXI = BLOCKS.register("zones_board_taxi", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_NON_MOTOR_VEHICLES = BLOCKS.register("zones_board_non_motor_vehicles", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_CHARGING = BLOCKS.register("zones_board_charging", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_DISABLED = BLOCKS.register("zones_board_disabled", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_SEMI_TRAILER = BLOCKS.register("zones_board_semi_trailer", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_CENTRAL_AXLE_TRAILER = BLOCKS.register("zones_board_central_axle_trailer", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_MEDIUM_SIZED_BUS = BLOCKS.register("zones_board_medium_sized_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TOURIST_BUS = BLOCKS.register("zones_board_tourist_bus", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TRUCKS_KEEP_RIGHT = BLOCKS.register("zones_board_trucks_keep_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_LARGE_TRUCKS_KEEP_RIGHT = BLOCKS.register("zones_board_large_trucks_keep_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_SCHOOL = BLOCKS.register("zones_board_school", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_PORT = BLOCKS.register("zones_board_port", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_COMPANY = BLOCKS.register("zones_board_company", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_RAMP = BLOCKS.register("zones_board_ramp", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TRUCK_ROAD = BLOCKS.register("zones_board_truck_road", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TIME_RANGE_1 = BLOCKS.register("zones_board_time_range_1", () -> new ZonesBoardTimeRange1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TIME_RANGE_2 = BLOCKS.register("zones_board_time_range_2", () -> new ZonesBoardTimeRange2(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_DISTANCE_LENGTH = BLOCKS.register("zones_board_distance_length", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_DISTANCE_LENGTH_LEFT = BLOCKS.register("zones_board_distance_length_left", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_DISTANCE_LENGTH_RIGHT = BLOCKS.register("zones_board_distance_length_right", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_TIME_LIMIT = BLOCKS.register("zones_board_time_limit", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_OVER_WEIGHT = BLOCKS.register("zones_board_over_weight", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_SUGGESTED_SPEED = BLOCKS.register("zones_board_suggested_speed", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_LENGTH = BLOCKS.register("zones_board_length", () -> new ZonesBoardOverWeight(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> ZONES_BOARD_IMAGE = BLOCKS.register("zones_board_image", () -> new ZonesBoardImage(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_LEFT = BLOCKS.register("sign_guide_intersection_advance_warning_1_wuhan_left", () -> new SignGuideIntersectionAdvanceWarning1Wuhan(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_STRAIGHT = BLOCKS.register("sign_guide_intersection_advance_warning_1_wuhan_straight", () -> new SignGuideIntersectionAdvanceWarning1Wuhan(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_RIGHT = BLOCKS.register("sign_guide_intersection_advance_warning_1_wuhan_right", () -> new SignGuideIntersectionAdvanceWarning1Wuhan(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1 = BLOCKS.register("sign_guide_intersection_advance_warning_1", () -> new SignGuideIntersectionAdvanceWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_2 = BLOCKS.register("sign_guide_intersection_advance_warning_2", () -> new SignGuideIntersectionAdvanceWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_3 = BLOCKS.register("sign_guide_intersection_advance_warning_3", () -> new SignGuideIntersectionAdvanceWarning3(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_4 = BLOCKS.register("sign_guide_intersection_advance_warning_4", () -> new SignGuideIntersectionAdvanceWarning3(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_5 = BLOCKS.register("sign_guide_intersection_advance_warning_5", () -> new SignGuideIntersectionAdvanceWarning5(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_6 = BLOCKS.register("sign_guide_intersection_advance_warning_6", () -> new SignGuideIntersectionAdvanceWarning6(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_7 = BLOCKS.register("sign_guide_intersection_advance_warning_7", () -> new SignGuideIntersectionAdvanceWarning7(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_8 = BLOCKS.register("sign_guide_intersection_advance_warning_8", () -> new SignGuideIntersectionAdvanceWarning6(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_1 = BLOCKS.register("sign_guide_intersection_warning_1", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_2 = BLOCKS.register("sign_guide_intersection_warning_2", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_3 = BLOCKS.register("sign_guide_intersection_warning_3", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_4 = BLOCKS.register("sign_guide_intersection_warning_4", () -> new SignGuideIntersectionWarning4(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_5 = BLOCKS.register("sign_guide_intersection_warning_5", () -> new SignGuideIntersectionWarning4(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_INTERSECTION_WARNING_6 = BLOCKS.register("sign_guide_intersection_warning_6", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_GUIDE_CONFIRMATION_1 = BLOCKS.register("sign_guide_confirmation_1", () -> new SignGuideConfirmation1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_CONFIRMATION_2 = BLOCKS.register("sign_guide_confirmation_2", () -> new SignGuideConfirmation1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_GUIDE_LANE_INDICATOR_1 = BLOCKS.register("sign_guide_lane_indicator_1", () -> new SignGuideLaneIndicator1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_FIRST_AID_STATION = BLOCKS.register("sign_guide_identification_first_aid_station", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_AIRPORT_LEFT = BLOCKS.register("sign_guide_identification_airport_left", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_AIRPORT_RIGHT = BLOCKS.register("sign_guide_identification_airport_right", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_GAS_STATION = BLOCKS.register("sign_guide_identification_gas_station", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_CHARGING = BLOCKS.register("sign_guide_identification_charging", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_METRO = BLOCKS.register("sign_guide_identification_metro", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IDENTIFICATION_FERRY_CROSSING = BLOCKS.register("sign_guide_identification_ferry_crossing", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_1 = BLOCKS.register("sign_guide_roadside_facility_parking_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_2 = BLOCKS.register("sign_guide_roadside_facility_parking_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_WRONG_LANE = BLOCKS.register("sign_guide_roadside_facility_wrong_lane", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_HARBOR_STYLE_EMERGENCY_PARKING_LANE = BLOCKS.register("sign_guide_roadside_facility_harbor_style_emergency_parking_lane", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PEDESTRIAN_OVERPASS = BLOCKS.register("sign_guide_roadside_facility_pedestrian_overpass", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PEDESTRIAN_UNDERPASS = BLOCKS.register("sign_guide_roadside_facility_pedestrian_underpass", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_DISABLED = BLOCKS.register("sign_guide_roadside_facility_disabled", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_SERVICE_STATION_1 = BLOCKS.register("sign_guide_roadside_facility_service_station_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_SERVICE_STATION_2 = BLOCKS.register("sign_guide_roadside_facility_service_station_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_SPOT_1 = BLOCKS.register("sign_guide_roadside_facility_parking_spot_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_SPOT_2 = BLOCKS.register("sign_guide_roadside_facility_parking_spot_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_VIEWING_PLATFORM_1 = BLOCKS.register("sign_guide_roadside_facility_viewing_platform_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_VIEWING_PLATFORM_2 = BLOCKS.register("sign_guide_roadside_facility_viewing_platform_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_EMERGENCY_ESCAPE_FACILITIES = BLOCKS.register("sign_guide_roadside_facility_emergency_escape_facilities", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_OVERLOAD_CHECKPOINT_1 = BLOCKS.register("sign_guide_roadside_facility_overload_checkpoint_1", () -> new SignGuideRoadsideFacilityOverloadCheckpoint1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ROADSIDE_FACILITY_OVERLOAD_CHECKPOINT_2 = BLOCKS.register("sign_guide_roadside_facility_overload_checkpoint_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DETOUR_1 = BLOCKS.register("sign_guide_detour_1", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DETOUR_2 = BLOCKS.register("sign_guide_detour_2", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DETOUR_3 = BLOCKS.register("sign_guide_detour_3", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_IMPASSABLE_ROAD = BLOCKS.register("sign_guide_impassable_road", () -> new SignSimpleBlock(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_1 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_1", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_2 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_2", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_3 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_3", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_4 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_4", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_5 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_5", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_6 = BLOCKS.register("sign_guide_distance_to_tunnel_exit_6", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_GUIDE_ODOMETER = BLOCKS.register("sign_guide_odometer", () -> new SignGuideIntersectionWarning1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_1 = BLOCKS.register("sign_expressway_entrance_advance_1", () -> new SignExpresswayEntranceAdvance1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_2 = BLOCKS.register("sign_expressway_entrance_advance_2", () -> new SignExpresswayEntranceAdvance1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_3 = BLOCKS.register("sign_expressway_entrance_advance_3", () -> new SignExpresswayEntranceAdvance1(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_4 = BLOCKS.register("sign_expressway_entrance_advance_4", () -> new SignExpresswayEntranceAdvance4(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_5 = BLOCKS.register("sign_expressway_entrance_advance_5", () -> new SignExpresswayEntranceAdvance4(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_6 = BLOCKS.register("sign_expressway_entrance_advance_6", () -> new SignExpresswayEntranceAdvance4(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_7 = BLOCKS.register("sign_expressway_entrance_advance_7", () -> new SignExpresswayEntranceAdvance7(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_8 = BLOCKS.register("sign_expressway_entrance_advance_8", () -> new SignExpresswayEntranceAdvance7(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_9 = BLOCKS.register("sign_expressway_entrance_advance_9", () -> new SignExpresswayEntranceAdvance7(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_10 = BLOCKS.register("sign_expressway_entrance_advance_10", () -> new SignExpresswayEntranceAdvance10(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_11 = BLOCKS.register("sign_expressway_entrance_advance_11", () -> new SignExpresswayEntranceAdvance10(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_12 = BLOCKS.register("sign_expressway_entrance_advance_12", () -> new SignExpresswayEntranceAdvance10(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_13 = BLOCKS.register("sign_expressway_entrance_advance_13", () -> new SignExpresswayEntranceAdvance13(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_14 = BLOCKS.register("sign_expressway_entrance_advance_14", () -> new SignExpresswayEntranceAdvance13(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_15 = BLOCKS.register("sign_expressway_entrance_advance_15", () -> new SignExpresswayEntranceAdvance13(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));
    public static final RegistrySupplier<Block> SIGN_EXPRESSWAY_EXIT_8 = BLOCKS.register("sign_expressway_exit_8", () -> new SignExpresswayExit8(AbstractBlock.Settings.copy(Blocks.CYAN_TERRACOTTA).nonOpaque().requiresTool()));

    public static void init() {
        BLOCKS.register();
    }
}
