package com.beigu.yunbeiuc.fabric.client;

import com.beigu.yunbeiuc.block.MunicipalBlocks;
import com.beigu.yunbeiuc.block.RoadBlocks;
import com.beigu.yunbeiuc.block.SignBlocks;
import com.beigu.yunbeiuc.entity.ModBlockEntities;
import com.beigu.yunbeiuc.render.*;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.block.entity.BlockEntityRendererFactories;


public final class YunbeiUrbanConstructionFabricClient implements ClientModInitializer {
    @Override
    public void onInitializeClient() {
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STRAIGHT_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STRAIGHT_LEFT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LEFT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STRAIGHT_RIGHT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.RIGHT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STRAIGHT_LEFT_RIGHT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LEFT_TURN_AROUND_SINGLE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STRAIGHT_LEFT_TURN_AROUND_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LEFT_TURN_AROUND_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LEFT_RIGHT_TURN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LEFT_TURN_MERGE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.RIGHT_TURN_MERGE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.SLOWDOWN_ANNOUNCEMENT_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.DISTANCE_CONFIRMATION_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.TAXI_1_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.TAXI_2_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.VEHICLE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.DISABLED_PEOPLE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.NON_MOTOR_VEHICLES_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.BUS_1_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.BUS_2_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.SCHOOL_BUS_1_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.LARGE_SPEED_BUMP_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.SMALL_SPEED_BUMP_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_040_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_050_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_060_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_070_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_080_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_090_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_100_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_110_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.WHITE_120_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_040_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_050_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_060_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_070_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_080_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_090_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_100_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_110_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.YELLOW_120_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.ELECTRIC_VEHICLE_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.PEDESTRIAN_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.STOP_AND_YIELD_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.HOV_1_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.HOV_2_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.HOV_3_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.HOV_4_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.HOV_5_GROUND_MARK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(RoadBlocks.MANHOLE_COVER.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.ROAD_FLOWER_BOX_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.ROAD_FLOWER_BOX_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.ROAD_FLOWER_BOX_2_FENCE.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.ANTI_GLARE_NET.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.ANTI_GLARE_NET_POLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.WARNING_NETWORK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.WARNING_NETWORK_POLE.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.TRAFFIC_LIGHTS_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.TRAFFIC_LIGHTS_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.TRAFFIC_LIGHTS_PAVEMENT.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_WHITE_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_WHITE_TB.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_BLUE_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_BLUE_TB.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_GREEN_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_1_GREEN_TB.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_2_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_2_TB.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_3_WHITE_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_3_WHITE_TB.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_3_BLUE_NORMAL.get(), RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(MunicipalBlocks.SOUND_BARRIER_3_BLUE_TB.get(), RenderLayer.getTranslucent());

        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_10.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_20.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_ALEX_WEIGHT_LIMIT_30.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_OVERTAKE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_005.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_010.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_020.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_030.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_040.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_050.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_060.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_070.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_080.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_090.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_100.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_110.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CANCEL_SPEED_LIMIT_120.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_CHECK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_20.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_25.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_30.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_35.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_40.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_HEIGHT_LIMIT_45.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ELECTRIC_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_HEADLIGHTS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_HONK_HORN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_ELECTRIC_VEHICLE_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_HOV.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_BRT_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LARGE_BUS_TEXT_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_LEFT_TURN_AROUND.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_MOTOR_VEHICLES_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_NON_MOTOR_VEHICLES_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SINGLE_LEFT_TURN_AROUND.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_SMALL_PASSENGER_CAR_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_STRAIGHT_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LANE_DIRECTION_TRAM_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LEFT_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LEFT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_OK_TRUCK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ONE_WAY_STREET_LEFT_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ONE_WAY_STREET_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_4.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_CHARGING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_DISABLED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_SCHOOL_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_SCHOOL_BUS_FLUORESCENCE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PARKING_TAXI.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PAVED_SHOULDER_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PEDESTRIAN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PEDESTRIAN_NON_MOTOR_VEHICLES_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PROMOTION_DRIVE_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_PROMOTION_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_RIGHT_SIDE_MEDIAN_STRIP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ROUNDABOUT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_SCHOOL_BUS_WUXI.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_STRAIGHT_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_STRAIGHT_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_TURN_AROUND.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_YIELD_TO_ONCOMING_TRAFFIC.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ZEBRA_CROSSING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_INDICATION_ZEBRA_CROSSING_FLUORESCENCE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_005.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_010.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_020.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_030.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_040.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_050.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_060.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_070.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_080.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_090.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_MIN_SPEED_LIMIT_100.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_ALL.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_ANIMAL_DRAWN_CART.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_ELECTRIC_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_ENTRY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_HAZARDOUS_MATERIALS_TRANSPORT_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_HONK_HORN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_HUMAN_POWERED_CARGO_TRICYCLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_HUMAN_POWERED_PASSENGER_TRICYCLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_LARGE_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_LEFT_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_MOTORCYCLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_OVERTAKE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_PARKING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_PARKING_LONG_TIME.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_PEDESTRIAN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_RICKSHAW.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_SINGLE_LEFT_TURN_AROUND.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_SMALL_PASSENGER_CAR.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_STRAIGHT_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_STRAIGHT_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_THREE_WHEELED_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_TRACTOR.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_TRAILER.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_TRICYCLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_NO_TRUCK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_PORT_CHECK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_005.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_010.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_020.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_030.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_040.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_050.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_060.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_070.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_080.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_090.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_100.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_110.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_SPEED_LIMIT_120.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_STOP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LESS_3_TO_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LESS_4_TO_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ACCIDENT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ACCIDENT_PRONE_ROAD.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CAMEL_BACK_BRIDGE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CHILDREN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CHILDREN_FLUORESCENCE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONFLUENCE_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONFLUENCE_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONSTRUCTION.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONTINUOUS_DOWNHILL.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONTINUOUS_WINDING_ROADS_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CONTINUOUS_WINDING_ROADS_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_10.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_11.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_4.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_5.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_6.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_7.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_8.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSING_9.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_CROSSWIND.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DANGEROUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DETOUR_DOUBLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DETOUR_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DETOUR_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DISABLED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DISABLED_FLUORESCENCE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_DISTANCE_BETWEEN_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ELECTRIC_VEHICLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_EMBANKMENT_ROAD_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_EMBANKMENT_ROAD_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_EMERGENCY_LANE_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_EMERGENCY_LANE_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_FALLING_ROCKS_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_FALLING_ROCKS_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LIVESTOCK.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_NARROW_BRIDGE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_NARROW_ROAD_DOUBLE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_NARROW_ROAD_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_NARROW_ROAD_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_PERILOUS_ROAD_ALONG_THE_MOUNTAIN_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_REVERSE_DETOUR_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_REVERSE_DETOUR_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ROAD_ICY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ROAD_UNEVEN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ROAD_WET.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_SHARP_TURN_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_SHARP_TURN_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_SLIPPERY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_SOMEONE_GUARDING_THE_RAILWAY_CROSSING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_SPEED_BUMP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_STEEP_SLOPE_DOWN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_STEEP_SLOPE_UP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_TIDAL_LANE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_TRAFFIC_LIGHTS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_TUNNEL.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_TWO_WAY_TRAFFIC.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_UNMANNED_GUARDING_THE_RAILWAY_CROSSING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_VEHICLES_QUEUED_AHEAD.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_VILLAGE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_WEATHER_FOGGY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_WEATHER_RAINY_SNOWY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_WEATHER_THUNDER.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_WILDLIFE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ZEBRA_CROSSING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_ZEBRA_CROSSING_FLUORESCENCE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_4.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_5.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_6.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_7.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_8.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WARNING_LINEAR_GUIDANCE_MARKER_9.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WEIGHT_LIMIT_10.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WEIGHT_LIMIT_20.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WEIGHT_LIMIT_30.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WEIGHT_LIMIT_40.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_20.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_25.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_30.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_35.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_40.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_WIDTH_LIMIT_45.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_YIELD.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_YIELD_TO_ONCOMING_TRAFFIC.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_RED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_YELLOW.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_WHITE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_LEFT_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_STRAIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_LEFT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_ARROW_RIGHT_TURN.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_SCHOOL_BUS_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_SCHOOL_BUS_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TAXI.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_NON_MOTOR_VEHICLES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_CHARGING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_DISABLED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_SEMI_TRAILER.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_CENTRAL_AXLE_TRAILER.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_MEDIUM_SIZED_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TOURIST_BUS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TRUCKS_KEEP_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_LARGE_TRUCKS_KEEP_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_SCHOOL.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_PORT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_COMPANY.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_RAMP.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TRUCK_ROAD.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TIME_RANGE_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TIME_RANGE_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_DISTANCE_LENGTH.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_DISTANCE_LENGTH_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_DISTANCE_LENGTH_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_TIME_LIMIT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_OVER_WEIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_SUGGESTED_SPEED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_LENGTH.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.ZONES_BOARD_IMAGE.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_LEFT.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_STRAIGHT.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_RIGHT.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_2.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_3.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_4.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_5.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_6.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_7.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_8.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_1.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_2.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_3.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_4.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_5.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_INTERSECTION_WARNING_6.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_CONFIRMATION_1.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_CONFIRMATION_2.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_LANE_INDICATOR_1.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_FIRST_AID_STATION.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_AIRPORT_LEFT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_AIRPORT_RIGHT.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_GAS_STATION.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_CHARGING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_METRO.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IDENTIFICATION_FERRY_CROSSING.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_WRONG_LANE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_HARBOR_STYLE_EMERGENCY_PARKING_LANE.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PEDESTRIAN_OVERPASS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PEDESTRIAN_UNDERPASS.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_DISABLED.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_SERVICE_STATION_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_SERVICE_STATION_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_SPOT_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_PARKING_SPOT_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_VIEWING_PLATFORM_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_VIEWING_PLATFORM_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_EMERGENCY_ESCAPE_FACILITIES.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_OVERLOAD_CHECKPOINT_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ROADSIDE_FACILITY_OVERLOAD_CHECKPOINT_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DETOUR_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DETOUR_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DETOUR_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_IMPASSABLE_ROAD.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_1.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_2.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_3.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_4.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_5.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_DISTANCE_TO_TUNNEL_EXIT_6.get(), RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_GUIDE_ODOMETER.get(), RenderLayer.getCutout());

        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_1.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_2.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_3.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_4.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_5.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_6.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_7.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_8.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_9.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_10.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_11.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_12.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_13.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_14.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_15.get(),RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SignBlocks.SIGN_EXPRESSWAY_EXIT_8.get(),RenderLayer.getCutout());

        BlockEntityRendererFactories.register(ModBlockEntities.ROAD_POLE_TEXT_DISPLAY_ENTITY.get(), RoadPoleTextDisplayBlockEntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.FLAG_BLOCK_ENTITY.get(), FlagBlockEntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ROAD_NAME_SIGN_BLOCK_ENTITY.get(), RoadNameSignBlockEntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_WUHAN_ENTITY.get(), SignGuideIntersectionAdvanceWarning1WuhanEntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_1_ENTITY.get(), SignGuideIntersectionAdvanceWarning1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_3_ENTITY.get(), SignGuideIntersectionAdvanceWarning3EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_5_ENTITY.get(), SignGuideIntersectionAdvanceWarning5EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_6_ENTITY.get(), SignGuideIntersectionAdvanceWarning6EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_ADVANCE_WARNING_7_ENTITY.get(), SignGuideIntersectionAdvanceWarning7EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_WARNING_1_ENTITY.get(), SignGuideIntersectionWarning1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_INTERSECTION_WARNING_4_ENTITY.get(), SignGuideIntersectionWarning4EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_CONFIRMATION_1_ENTITY.get(), SignGuideConfirmation1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_LANE_INDICATOR_1_ENTITY.get(), SignGuideLaneIndicator1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_GUIDE_ROADSIDE_FACILITY_OVERLOAD_CHECKPOINT_1_ENTITY.get(), SignGuideRoadsideFacilityOverloadCheckpoint1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_1_ENTITY.get(), SignExpresswayEntranceAdvance1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_4_ENTITY.get(), SignExpresswayEntranceAdvance4EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_7_ENTITY.get(), SignExpresswayEntranceAdvance7EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_10_ENTITY.get(), SignExpresswayEntranceAdvance10EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_ENTRANCE_ADVANCE_13_ENTITY.get(), SignExpresswayEntranceAdvance13EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.SIGN_EXPRESSWAY_EXIT_8_ENTITY.get(), SignExpresswayExit8EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ZONES_BOARD_1_ENTITY.get(), ZonesBoard1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ZONES_BOARD_IMAGE_ENTITY.get(), ZonesBoardImageEntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ZONES_BOARD_TIME_RANGE_1_ENTITY.get(), ZonesBoardTimeRange1EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ZONES_BOARD_TIME_RANGE_2_ENTITY.get(), ZonesBoardTimeRange2EntityRenderer::new);
        BlockEntityRendererFactories.register(ModBlockEntities.ZONES_BOARD_OVER_WEIGHT_ENTITY.get(), ZonesBoardOverWeightEntityRenderer::new);
    }
}
